spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        wiretap: true
      routes:
        - id: employee
          uri: lb://employee
          predicates:
            - Path=/employee/**
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
        - id: department
          uri: lb://department
          predicates:
            - Path=/department/**
          filters:
            - RewritePath=/department/(?<path>.*), /$\{path}
        - id: organization
          uri: lb://organization
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.cloud.gateway: DEBUG
    #    org.springframework.http.server.reactive: DEBUG
    #    org.springframework.web.reactive: DEBUG
    #    org.springframework.cloud.loadbalancer: TRACE
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server.AccessLog: INFO
management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true
reactor:
  netty:
    http:
      server:
        accessLogEnabled: true

